// config/navigation.ts (actualizado)
import type { NavLinkGroup } from '@/types/navigation';
import {
  Car,
  Users,
  Wrench,
  Package,
  FileText,
  MessageSquare,
  QrCode,
  Settings,
  Home,
  User,
  ArrowLeftRight,
  Shield,
} from 'lucide-react';

export const navLinkGroups: NavLinkGroup[] = [
  {
    title: 'Administración',
    roles: ['ADMIN'],
    icon: Settings,
    links: [
      {
        href: '/dashboard/admin',
        icon: Home,
        label: 'Inicio',
        roles: ['ADMIN'],
        description: 'Panel de control administrativo',
      },
      {
        href: '/dashboard/admin/mechanics',
        icon: Users,
        label: 'Mecánicos',
        roles: ['ADMIN'],
        description: 'Gestión de mecánicos',
      },
      {
        href: '/dashboard/admin/inventory',
        icon: Package,
        label: 'Inventario',
        roles: ['ADMIN'],
        description: 'Gestión de repuestos',
      },
      {
        href: '/dashboard/admin/transfers',
        icon: ArrowLeftRight,
        label: 'Traspasos',
        roles: ['ADMIN'],
        description: 'Administrar traspasos de vehículos',
      },
    ],
  },
  {
    title: 'Área de Mecánico',
    roles: ['MECHANIC'],
    icon: Wrench,
    links: [
      {
        href: '/dashboard/mechanic',
        icon: Home,
        label: 'Inicio',
        roles: ['MECHANIC'],
        description: 'Panel de control del mecánico',
      },
      {
        href: '/dashboard/mechanic/scanner',
        icon: QrCode,
        label: 'Escanear QR',
        roles: ['MECHANIC'],
        description: 'Escanear código QR del vehículo',
      },
      {
        href: '/dashboard/mechanic/history',
        icon: Wrench,
        label: 'Historial',
        roles: ['MECHANIC'],
        description: 'Historial de mantenimientos',
      },
      {
        href: '/dashboard/mechanic/chat',
        icon: MessageSquare,
        label: 'Chat',
        roles: ['MECHANIC'],
        description: 'Comunicación con propietarios',
      },
    ],
  },
  {
    title: 'Área del Propietario',
    roles: ['OWNER'],
    icon: Car,
    links: [
      {
        href: '/dashboard/owner/vehicles',
        icon: Car,
        label: 'Mis Vehículos',
        roles: ['OWNER'],
        description: 'Gestión de vehículos',
        subLinks: [
          {
            href: '/dashboard/owner/vehicles/[id]',
            label: 'Detalle del Vehículo',
            description: 'Ver detalles completos del vehículo',
            roles: ['OWNER'],
            isSubLink: true,
            parentHref: '/dashboard/owner/vehicles',
            icon: Car,
          },
          {
            href: '/dashboard/owner/vehicles/[id]/qr',
            label: 'Código QR',
            description: 'Ver código QR del vehículo',
            roles: ['OWNER'],
            isSubLink: true,
            parentHref: '/dashboard/owner/vehicles',
            icon: QrCode,
          },
          {
            href: '/dashboard/owner/vehicles/[id]/transfer',
            label: 'Iniciar Traspaso',
            description: 'Transferir vehículo a otro propietario',
            roles: ['OWNER'],
            isSubLink: true,
            parentHref: '/dashboard/owner/vehicles',
            icon: ArrowLeftRight,
          },
        ],
      },
      {
        href: '/dashboard/owner/transfers',
        icon: ArrowLeftRight,
        label: 'Traspasos',
        roles: ['OWNER'],
        description: 'Gestión de traspasos de vehículos',
        subLinks: [
          {
            href: '/dashboard/owner/transfers/[id]',
            label: 'Detalle del Traspaso',
            description: 'Ver detalles completos del traspaso',
            roles: ['OWNER'],
            isSubLink: true,
            parentHref: '/dashboard/owner/transfers',
            icon: FileText,
          },
        ],
      },
      {
        href: '/dashboard/owner/documents',
        icon: FileText,
        label: 'Documentos',
        roles: ['OWNER'],
        description: 'Gestión de documentos vehiculares',
      },
      {
        href: '/dashboard/owner/chat',
        icon: MessageSquare,
        label: 'Chat',
        roles: ['OWNER'],
        description: 'Comunicación con mecánicos',
      },
    ],
  },
  {
    title: 'Mi Cuenta',
    roles: ['ADMIN', 'MECHANIC', 'OWNER'],
    icon: User,
    links: [
      {
        href: '/dashboard/profile',
        icon: User,
        label: 'Mi Perfil',
        roles: ['ADMIN', 'MECHANIC', 'OWNER'],
        description: 'Gestionar información personal',
      },
    ],
  },
];
